AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  GitHubToken:
    Type: String
    NoEcho: true
    Description: GitHub Personal Access Token (used by Lambda to create PRs)

  GitHubRepo:
    Type: String
    Description: GitHub repository in format owner/repo (e.g. user/project)

  StageName:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: Deployment stage/environment name

Resources:
  Topic:
    Type: AWS::SNS::Topic
    Properties:
      Tags:
        - Key: Project
          Value: ServerlessRDS
        - Key: Environment
          Value: !Ref StageName

  Queue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 60
      Tags:
        - Key: Project
          Value: ServerlessRDS
        - Key: Environment
          Value: !Ref StageName

  Subscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: sqs
      TopicArn: !Ref Topic
      Endpoint: !GetAtt Queue.Arn
      RawMessageDelivery: true

  QueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues: [!Ref Queue]
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: sns.amazonaws.com
            Action: sqs:SendMessage
            Resource: !GetAtt Queue.Arn

  Lambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/
      Handler: handler.lambda_handler
      Runtime: python3.13
      Timeout: 30
      Environment:
        Variables:
          GITHUB_TOKEN: !Ref GitHubToken
          GITHUB_REPO: !Ref GitHubRepo
          ENV: !Ref StageName
      Events:
        SQS:
          Type: SQS
          Properties:
            Queue: !GetAtt Queue.Arn
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: "*"
      Tags:
        Project: ServerlessRDS
        Environment: !Ref StageName

  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref StageName
      Auth:
        ApiKeyRequired: true
      DefinitionBody:
        openapi: 3.0.1
        paths:
          /request-rds:
            post:
              security:
                - api_key: []
              x-amazon-apigateway-integration:
                type: aws
                httpMethod: POST
                uri: !Sub "arn:aws:apigateway:${AWS::Region}:sns:action/Publish"
                credentials: !GetAtt ApiRole.Arn
                requestTemplates:
                  application/json: !Sub "TopicArn=${Topic}&Message=$input.body"
                responses:
                  default:
                    statusCode: 200
        securityDefinitions:
          api_key:
            type: apiKey
            name: x-api-key
            in: header

  ApiKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Name: !Sub "${AWS::StackName}-api-key"
      Enabled: true

  UsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      UsagePlanName: !Sub "${AWS::StackName}-usage-plan"
      ApiStages:
        - ApiId: !Ref Api
          Stage: !Ref StageName
      Throttle:
        RateLimit: 100
        BurstLimit: 200

  UsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref ApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref UsagePlan

  ApiRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: SNSPublish
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action: sns:Publish
                Resource: !Ref Topic

Outputs:
  ApiUrl:
    Value: !Sub "https://${Api}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/request-rds"
    Description: "API endpoint to request RDS cluster"
  ApiKey:
    Value: !Ref ApiKey
    Description: "API Key for client access"
