AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  GitHubToken:
    Type: String
    NoEcho: true
    Default: ""

Resources:

  Topic:
    Type: AWS::SNS::Topic

  Queue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 60

  Subscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: sqs
      TopicArn: !Ref Topic
      Endpoint: !GetAtt Queue.Arn

  QueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues: [!Ref Queue]
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: sns.amazonaws.com
            Action: sqs:SendMessage
            Resource: !GetAtt Queue.Arn

  Lambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/
      Handler: handler.lambda_handler
      Runtime: python3.11
      Timeout: 30
      Environment:
        Variables:
          GITHUB_TOKEN: !Ref GitHubToken
          GITHUB_REPO: !Sub "${AWS::StackName}"
      Events:
        SQS:
          Type: SQS
          Properties:
            Queue: !GetAtt Queue.Arn
      Policies:
        - CloudWatchLogsFullAccess

  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Auth:
        ApiKeyRequired: true
      DefinitionBody:
        openapi: 3.0.1
        paths:
          /request-rds:
            post:
              security:
                - api_key: []
              x-amazon-apigateway-integration:
                type: aws
                httpMethod: POST
                uri: !Sub "arn:aws:apigateway:${AWS::Region}:sns:action/Publish"
                credentials: !GetAtt ApiRole.Arn
                requestTemplates:
                  application/json: !Sub "TopicArn=${Topic}&Message=$input.body"
                responses:
                  default:
                    statusCode: 200
        securityDefinitions:
          api_key:
            type: apiKey
            name: x-api-key
            in: header

  ApiKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Name: !Sub "${AWS::StackName}-api-key"
      Enabled: true

  UsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    DependsOn:
      - Api
    Properties:
      UsagePlanName: !Sub "${AWS::StackName}-usage-plan"
      ApiStages:
        - ApiId: !Ref Api
          Stage: prod
      Throttle:
        RateLimit: 100
        BurstLimit: 200

  UsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref ApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref UsagePlan

  ApiRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: SNSPublish
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action: sns:Publish
                Resource: !Ref Topic

Outputs:
  ApiUrl:
    Value: !Sub "https://${Api}.execute-api.${AWS::Region}.amazonaws.com/prod/request-rds"

  ApiKeyOutput:
    Value: !Ref ApiKey
    Description: "API Key for authentication"
